### ISSUE TITLE
Cannot have `validate` and `no_std` with `-Z build-std`

### ISSUE THREAD

**Issue by mamins1376** [rkyv/rkyv#225]
I'm using a custom rustc ([esp-rs/rust](https://github.com/esp-rs/rust) to be specific) and can't afford to use the standard library. Evidently, `bytecheck` and `ptr_meta` have `std` feature enabled by default ([here](https://github.com/rkyv/bytecheck/blob/master/bytecheck/Cargo.toml#L31) and [here](https://github.com/rkyv/ptr_meta/blob/master/ptr_meta/Cargo.toml#L20)) which leads to this error:

```
   ...
   Compiling ptr_meta v0.1.4
error[E0658]: use of unstable library feature 'restricted_std'
  |
  = help: add `#![feature(restricted_std)]` to the crate attributes to enable

For more information about this error, try `rustc --explain E0658`.
error: could not compile `ptr_meta` due to previous error
```

... which indicates that a crate is not doing `#![no_std]`. I can `extern crate alloc` though.

Enabled features:
```toml
[dependencies.rkyv]
version = "0.7.22"
default_features = false
features = ["strict", "size_32", "validation", "alloc"]
```

This library already amazes me. Thanks!

**Comment by djkoloski** [comment]
Thanks for the bug report, I'll try to get a repro on this as soon as possible. If I remember correctly, rkyv should have the default features for bytecheck and ptr_meta disabled. Are you pulling in bytecheck explicitly through a dep? If so, you may need to set `default-features = false`.

**Comment by djkoloski** [comment]
Just took a peek at `bytecheck` and it looks like that might be what's pulling in `std` since it doesn't disable `ptr_meta`'s default features. I can see if that's what's causing it in a few hours.

**Comment by mamins1376** [comment]
> Are you pulling in bytecheck explicitly through a dep?

Not at the moment, I only enabled `validation` on rkyv that this happened.

**Comment by mamins1376** [comment]
FYI, this is an ongoing struggle with optional features and dependencies. See [related question](https://stackoverflow.com/q/52825268/4491972) and [tracking issue](https://github.com/rust-lang/cargo/issues/8832).

I thought there might be a workaround, at least for the time being.

**Comment by djkoloski** [comment]
It turned out to be due to bytecheck using the default features of ptr_meta. This has been fixed in bytecheck 0.6.6. Running `cargo update` should fix the problem.

**Comment by mamins1376** [comment]
After update the problem still persisted, so I cloned rkyv and ran these:
```bash
$ git show-branch --sha1-name
[0a9394b] Merge branch 'master' of https://github.com/rkyv/rkyv

$ cargo build -p rkyv --target xtensa-esp8266-none-elf -Z build-std --release --no-default-features --features size_32,validation
   ...
   Compiling ptr_meta v0.1.4
error[E0658]: use of unstable library feature 'restricted_std'
  |
  = help: add `#![feature(restricted_std)]` to the crate attributes to enable

For more information about this error, try `rustc --explain E0658`.
error: could not compile `ptr_meta` due to previous error

```

**Comment by mamins1376** [comment]
The problem is indeed still `ptr_meta` having `std` enabled.

Without `validation`:
```bash
$ cargo tree -p rkyv --target xtensa-esp8266-none-elf -Z build-std --no-default-features --features size_32 -e all
rkyv v0.7.23 (...)
├── ptr_meta v0.1.4
│   └── ptr_meta_derive feature "default"
│       └── ptr_meta_derive v0.1.4 (proc-macro)
│           ├── proc-macro2 feature "default"
│           │   ├── proc-macro2 v1.0.32
│           │   │   └── unicode-xid feature "default"
│           │   │       └── unicode-xid v0.2.2
│           │   └── proc-macro2 feature "proc-macro"
│           │       └── proc-macro2 v1.0.32 (*)
│           ├── quote feature "default"
│           │   ├── quote v1.0.10
│           │   │   └── proc-macro2 v1.0.32 (*)
│           │   └── quote feature "proc-macro"
│           │       ├── quote v1.0.10 (*)
│           │       └── proc-macro2 feature "proc-macro" (*)
│           ├── syn feature "default"
│           │   ├── syn v1.0.82
│           │   │   ├── proc-macro2 v1.0.32 (*)
│           │   │   ├── quote v1.0.10 (*)
│           │   │   └── unicode-xid feature "default" (*)
│           │   ├── syn feature "clone-impls"
│           │   │   └── syn v1.0.82 (*)
│           │   ├── syn feature "derive"
│           │   │   └── syn v1.0.82 (*)
│           │   ├── syn feature "parsing"
│           │   │   └── syn v1.0.82 (*)
│           │   ├── syn feature "printing"
│           │   │   ├── syn v1.0.82 (*)
│           │   │   └── syn feature "quote"
│           │   │       └── syn v1.0.82 (*)
│           │   └── syn feature "proc-macro"
│           │       ├── syn v1.0.82 (*)
│           │       ├── proc-macro2 feature "proc-macro" (*)
│           │       ├── quote feature "proc-macro" (*)
│           │       └── syn feature "quote" (*)
│           └── syn feature "full"
│               └── syn v1.0.82 (*)
├── rkyv_derive feature "default"
│   └── rkyv_derive v0.7.22 (proc-macro) (/C/Users/Amin/document/project/contrib/rkyv/rkyv_derive)
│       ├── proc-macro2 feature "default" (*)
│       ├── quote feature "default" (*)
│       └── syn feature "default" (*)
└── seahash feature "default"
    └── seahash v4.1.0
```

With `validation`:
```bash
$ cargo tree -p rkyv --target xtensa-esp8266-none-elf -Z build-std --no-default-features --features size_32,validation -e all
rkyv v0.7.23 (...)
├── bytecheck v0.6.5
│   ├── bytecheck_derive v0.6.5 (proc-macro)
│   │   ├── proc-macro2 feature "default"
│   │   │   ├── proc-macro2 v1.0.32
│   │   │   │   └── unicode-xid feature "default"
│   │   │   │       └── unicode-xid v0.2.2
│   │   │   └── proc-macro2 feature "proc-macro"
│   │   │       └── proc-macro2 v1.0.32 (*)
│   │   ├── quote feature "default"
│   │   │   ├── quote v1.0.10
│   │   │   │   └── proc-macro2 v1.0.32 (*)
│   │   │   └── quote feature "proc-macro"
│   │   │       ├── quote v1.0.10 (*)
│   │   │       └── proc-macro2 feature "proc-macro" (*)
│   │   └── syn feature "default"
│   │       ├── syn v1.0.82
│   │       │   ├── proc-macro2 v1.0.32 (*)
│   │       │   ├── quote v1.0.10 (*)
│   │       │   └── unicode-xid feature "default" (*)
│   │       ├── syn feature "clone-impls"
│   │       │   └── syn v1.0.82 (*)
│   │       ├── syn feature "derive"
│   │       │   └── syn v1.0.82 (*)
│   │       ├── syn feature "parsing"
│   │       │   └── syn v1.0.82 (*)
│   │       ├── syn feature "printing"
│   │       │   ├── syn v1.0.82 (*)
│   │       │   └── syn feature "quote"
│   │       │       └── syn v1.0.82 (*)
│   │       └── syn feature "proc-macro"
│   │           ├── syn v1.0.82 (*)
│   │           ├── proc-macro2 feature "proc-macro" (*)
│   │           ├── quote feature "proc-macro" (*)
│   │           └── syn feature "quote" (*)
│   └── ptr_meta feature "default"
│       ├── ptr_meta v0.1.4
│       │   └── ptr_meta_derive feature "default"
│       │       └── ptr_meta_derive v0.1.4 (proc-macro)
│       │           ├── proc-macro2 feature "default" (*)
│       │           ├── quote feature "default" (*)
│       │           ├── syn feature "default" (*)
│       │           └── syn feature "full"
│       │               └── syn v1.0.82 (*)
│       └── ptr_meta feature "std"
│           └── ptr_meta v0.1.4 (*)
├── ptr_meta v0.1.4 (*)
├── rend v0.3.4
│   └── bytecheck v0.6.5 (*)
├── hashbrown feature "default"
│   ├── hashbrown v0.11.2
│   │   └── ahash v0.7.6
│   │       └── once_cell feature "alloc"
│   │           ├── once_cell v1.8.0
│   │           └── once_cell feature "race"
│   │               └── once_cell v1.8.0
│   │       [build-dependencies]
│   │       └── version_check feature "default"
│   │           └── version_check v0.9.3
│   ├── hashbrown feature "ahash"
│   │   └── hashbrown v0.11.2 (*)
│   └── hashbrown feature "inline-more"
│       └── hashbrown v0.11.2 (*)
├── rkyv_derive feature "default"
│   └── rkyv_derive v0.7.22 (proc-macro) (/C/Users/Amin/document/project/contrib/rkyv/rkyv_derive)
│       ├── proc-macro2 feature "default" (*)
│       ├── quote feature "default" (*)
│       └── syn feature "default" (*)
└── seahash feature "default"
    └── seahash v4.1.0
```

**Comment by djkoloski** [comment]
That tree still has bytecheck 0.6.5 in it. It looks like I authored commits and made a release but forgot to `cargo publish` bytecheck 0.6.6. I'll have that published in a bit and will update this issue when I do. The github repo is updated so a git dependency should work until then. Sorry for the confusion and thanks for your patience.

**Comment by djkoloski** [comment]
It should be updated now!

**Comment by mamins1376** [comment]
Solved. Thanks!
