### ISSUE TITLE
Example for `rkyv_dyn` does not compile

### ISSUE THREAD

**Issue by stijnh** [rkyv/rkyv#375]
The following example for `rkyv_dyn` from the [README](https://github.com/rkyv/rkyv/blob/1aea469278da6bbed66c4dc20efd589c0b9059b6/rkyv_dyn/README.md)

```Rust
use rkyv::{
    archived_value,
    ser::{
        serializers::AllocSerializer,
        Serializer,
    },
    Archive,
    Archived,
    Deserialize,
    Infallible,
    Serialize,
};
use rkyv_dyn::archive_dyn;
use rkyv_typename::TypeName;

#[archive_dyn(deserialize)]
trait ExampleTrait {
    fn value(&self) -> String;
}

#[derive(Archive, Serialize, Deserialize)]
#[archive_attr(derive(TypeName))]
struct StringStruct(String);

#[archive_dyn]
impl ExampleTrait for StringStruct {
    fn value(&self) -> String {
        self.0.clone()
    }
}

impl ExampleTrait for Archived<StringStruct> {
    fn value(&self) -> String {
        self.0.as_str().to_string()
    }
}

#[derive(Archive, Serialize, Deserialize)]
#[archive_attr(derive(TypeName))]
struct IntStruct(i32);

#[archive_dyn(deserialize)]
impl ExampleTrait for IntStruct {
    fn value(&self) -> String {
        format!("{}", self.0)
    }
}

impl ExampleTrait for Archived<IntStruct> {
    fn value(&self) -> String {
        format!("{}", self.0)
    }
}

fn main() {
    let boxed_int = Box::new(IntStruct(42)) as Box<dyn SerializeExampleTrait>;
    let boxed_string = Box::new(StringStruct("hello world".to_string())) as Box<dyn SerializeExampleTrait>;
    let mut serializer = AllocSerializer::<256>::default();

    let int_pos = serializer.serialize_value(&boxed_int).unwrap()
    let string_pos = serializer.serialize_value(&boxed_string).unwrap();
    let buf = serializer.into_inner();

    let archived_int = unsafe { archived_value::<Box<dyn SerializeExampleTrait>>(buf.as_ref(), int_pos) };
    let archived_string = unsafe { archived_value::<Box<dyn SerializeExampleTrait>>(buf.as_ref(), string_pos) };
    assert_eq!(archived_int.value(), "42");
    assert_eq!(archived_string.value(), "hello world");

    let deserialized_int: Box<dyn SerializeExampleTrait> = archived_int.deserialize(&mut Infallible).unwrap();
    let deserialized_string: Box<dyn SerializeExampleTrait> = archived_string.deserialize(&mut Infallible).unwrap();
    assert_eq!(deserialized_int.value(), "42");
    assert_eq!(deserialized_string.value(), "hello world");
}
```

results in the following compile errors on rustc 1.70.0-nightly (5e1d3299a 2023-03-31):

```
error: expected `;`, found keyword `let`
  --> src/main.rs:60:66
   |
60 |     let int_pos = serializer.serialize_value(&boxed_int).unwrap()
   |                                                                  ^ help: add `;` here
61 |     let string_pos = serializer.serialize_value(&boxed_string).unwrap();
   |     --- unexpected token

error[E0277]: the size for values of type `(dyn SerializeExampleTrait + 'static)` cannot be known at compilation time
   --> src/main.rs:16:1
    |
16  | #[archive_dyn(deserialize)]
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^ doesn't have a size known at compile-time
    |
    = help: the trait `Sized` is not implemented for `(dyn SerializeExampleTrait + 'static)`
    = help: the trait `ptr_meta::Pointee` is implemented for `(dyn Any + 'static)`
    = note: required for `(dyn SerializeExampleTrait + 'static)` to implement `ptr_meta::Pointee`
note: required by a bound in `DeserializeDyn`
   --> /home/stijn/.cargo/registry/src/github.com-1ecc6299db9ec823/rkyv_dyn-0.7.41/src/lib.rs:292:29
    |
292 | pub trait DeserializeDyn<T: Pointee + ?Sized> {
    |                             ^^^^^^^ required by this bound in `DeserializeDyn`
    = note: this error originates in the attribute macro `archive_dyn` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: the size for values of type `(dyn SerializeExampleTrait + 'static)` cannot be known at compilation time
   --> src/main.rs:16:1
    |
16  | #[archive_dyn(deserialize)]
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^ doesn't have a size known at compile-time
    |
    = help: the trait `Sized` is not implemented for `(dyn SerializeExampleTrait + 'static)`
    = help: the trait `ptr_meta::Pointee` is implemented for `(dyn Any + 'static)`
    = note: required for `(dyn SerializeExampleTrait + 'static)` to implement `ptr_meta::Pointee`
note: required by a bound in `DeserializeUnsized`
   --> /home/stijn/.cargo/registry/src/github.com-1ecc6299db9ec823/rkyv-0.7.41/src/lib.rs:701:33
    |
701 | pub trait DeserializeUnsized<T: Pointee + ?Sized, D: Fallible + ?Sized>: ArchivePointee {
    |                                 ^^^^^^^ required by this bound in `DeserializeUnsized`
    = note: this error originates in the attribute macro `archive_dyn` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: the size for values of type `(dyn DeserializeExampleTrait + 'static)` cannot be known at compilation time
   --> src/main.rs:16:1
    |
16  | #[archive_dyn(deserialize)]
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^ doesn't have a size known at compile-time
    |
    = help: the trait `Sized` is not implemented for `(dyn DeserializeExampleTrait + 'static)`
    = help: the trait `ArchivePointee` is implemented for `(dyn DeserializeExampleTrait + 'static)`
    = note: required for `(dyn DeserializeExampleTrait + 'static)` to implement `ptr_meta::Pointee`
    = note: required for `(dyn DeserializeExampleTrait + 'static)` to implement `ArchivePointee`
note: required by a bound in `DeserializeUnsized`
   --> /home/stijn/.cargo/registry/src/github.com-1ecc6299db9ec823/rkyv-0.7.41/src/lib.rs:701:74
    |
701 | pub trait DeserializeUnsized<T: Pointee + ?Sized, D: Fallible + ?Sized>: ArchivePointee {
    |                                                                          ^^^^^^^^^^^^^^ required by this bound in `DeserializeUnsized`
    = note: this error originates in the attribute macro `archive_dyn` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: the size for values of type `(dyn SerializeExampleTrait + 'static)` cannot be known at compilation time
   --> src/main.rs:16:1
    |
16  | #[archive_dyn(deserialize)]
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^ doesn't have a size known at compile-time
    |
    = help: the trait `Sized` is not implemented for `(dyn SerializeExampleTrait + 'static)`
    = help: the trait `ptr_meta::Pointee` is implemented for `(dyn Any + 'static)`
    = note: required for `(dyn SerializeExampleTrait + 'static)` to implement `ptr_meta::Pointee`
note: required by a bound in `ArchiveUnsized`
   --> /home/stijn/.cargo/registry/src/github.com-1ecc6299db9ec823/rkyv-0.7.41/src/lib.rs:620:27
    |
620 | pub trait ArchiveUnsized: Pointee {
    |                           ^^^^^^^ required by this bound in `ArchiveUnsized`
    = note: this error originates in the attribute macro `archive_dyn` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: the size for values of type `(dyn DeserializeExampleTrait + 'static)` cannot be known at compilation time
   --> src/main.rs:16:1
    |
16  | #[archive_dyn(deserialize)]
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^ doesn't have a size known at compile-time
    |
    = help: the trait `Sized` is not implemented for `(dyn DeserializeExampleTrait + 'static)`
    = help: the trait `ptr_meta::Pointee` is implemented for `(dyn Any + 'static)`
    = note: required for `(dyn DeserializeExampleTrait + 'static)` to implement `ptr_meta::Pointee`
note: required by a bound in `ArchivePointee`
   --> /home/stijn/.cargo/registry/src/github.com-1ecc6299db9ec823/rkyv-0.7.41/src/lib.rs:681:27
    |
681 | pub trait ArchivePointee: Pointee {
    |                           ^^^^^^^ required by this bound in `ArchivePointee`
    = note: this error originates in the attribute macro `archive_dyn` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: the size for values of type `(dyn SerializeExampleTrait + 'static)` cannot be known at compilation time
   --> src/main.rs:16:1
    |
16  | #[archive_dyn(deserialize)]
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^ doesn't have a size known at compile-time
    |
    = help: the trait `Sized` is not implemented for `(dyn SerializeExampleTrait + 'static)`
    = help: the trait `ArchiveUnsized` is implemented for `(dyn SerializeExampleTrait + 'static)`
    = note: required for `(dyn SerializeExampleTrait + 'static)` to implement `ptr_meta::Pointee`
    = note: required for `(dyn SerializeExampleTrait + 'static)` to implement `ArchiveUnsized`
note: required by a bound in `SerializeUnsized`
   --> /home/stijn/.cargo/registry/src/github.com-1ecc6299db9ec823/rkyv-0.7.41/src/lib.rs:692:51
    |
692 | pub trait SerializeUnsized<S: Fallible + ?Sized>: ArchiveUnsized {
    |                                                   ^^^^^^^^^^^^^^ required by this bound in `SerializeUnsized`
    = note: this error originates in the attribute macro `archive_dyn` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: the size for values of type `(dyn SerializeExampleTrait + 'static)` cannot be known at compilation time
   --> src/main.rs:42:1
    |
42  | #[archive_dyn(deserialize)]
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^ doesn't have a size known at compile-time
    |
    = help: the trait `Sized` is not implemented for `(dyn SerializeExampleTrait + 'static)`
    = help: the trait `ptr_meta::Pointee` is implemented for `(dyn Any + 'static)`
    = note: required for `(dyn SerializeExampleTrait + 'static)` to implement `ptr_meta::Pointee`
note: required by a bound in `DeserializeDyn`
   --> /home/stijn/.cargo/registry/src/github.com-1ecc6299db9ec823/rkyv_dyn-0.7.41/src/lib.rs:292:29
    |
292 | pub trait DeserializeDyn<T: Pointee + ?Sized> {
    |                             ^^^^^^^ required by this bound in `DeserializeDyn`
    = note: this error originates in the attribute macro `archive_dyn` (in Nightly builds, run with -Z macro-backtrace for more info)

```

**Comment by djkoloski** [comment]
Sorry for the delay. The examples in the GitHub and crates.io READMEs fell out of date, the example [in the documentation](https://docs.rs/rkyv_dyn/latest/rkyv_dyn/trait.SerializeDyn.html#examples) is already correct. I've pushed a fix for those two READMEs in 29e2769050b31cfdf53fc7e7cdaefca08213c575, though they won't appear fixed on crates.io until the next publish.

**Comment by Nickersoft** [comment]
I'd just like to chime in here that using the latest example, I'm still getting errors:

![CleanShot 2024-02-03 at 21 08 09@2x](https://github.com/rkyv/rkyv/assets/2104129/40ae03b0-847d-425c-a44f-20536c9662a2)

![CleanShot 2024-02-03 at 21 08 21@2x](https://github.com/rkyv/rkyv/assets/2104129/ba820230-b48d-4ec9-933e-79c9a6061b81)
